# Generated by Django 4.2.4 on 2023-08-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('ProductName', models.CharField(max_length=100)),
                ('Vendor', models.CharField(max_length=100)),
                ('MRP', models.FloatField()),
                ('BatchNum', models.IntegerField()),
                ('BatchDate', models.DateField()),
                ('Quantity', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('approve', 'APPROVED'), ('pending', 'PENDING')], default='pending', max_length=200)),
            ],
        ),
    ]
